services:
  postgresql:
    image: postgis/postgis:16-master
    container_name: booklub-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: booklub
    ports:
      - "5432:5432"
    volumes:
      - ./docker-volumes/postgresql:/var/lib/postgresql/data
    networks:
      - booklub-network

  keycloak:
    build:
      context: ./docker/keycloak
      dockerfile: Dockerfile
    container_name: keycloak
    command: [ "start-dev", "--import-realm", "--features=scripts", "--spi-scripting-scripts-enabled=true" ]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=booklub-postgres
      - KC_DB_URL_DATABASE=booklub
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=${DB_PASSWORD}
      - KC_DB_URL_PORT=5432
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    networks:
      - booklub-network

  minio:
    image: quay.io/minio/minio
    container_name: booklub-minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 12345678
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./docker-volumes/minio:/data
    command: server /data --console-address ":9001"

networks:
  booklub-network:
